/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate user with email and password, returns JWT access and refresh tokens
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example user@example.com
                         */
                        email: string;
                        /**
                         * Format: password
                         * @example SecurePassword123!
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description JWT access token (expires in 15 minutes)
                             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                             */
                            access_token?: string;
                            /**
                             * @description JWT refresh token (expires in 7 days)
                             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                             */
                            refresh_token?: string;
                            /** @example Bearer */
                            token_type?: string;
                            /**
                             * @description Access token expiration time in seconds
                             * @example 900
                             */
                            expires_in?: number;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User registration
         * @description Register a new user account
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example newuser@example.com
                         */
                        email: string;
                        /**
                         * Format: password
                         * @example SecurePassword123!
                         */
                        password: string;
                        /** @example John Doe */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Registration successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token?: string;
                            refresh_token?: string;
                            /** @example Bearer */
                            token_type?: string;
                            /** @example 900 */
                            expires_in?: number;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description User already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "conflict",
                         *       "message": "User with this email already exists"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh JWT token
         * @description Exchange refresh token for a new access token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Token refreshed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token?: string;
                            /** @example Bearer */
                            token_type?: string;
                            /** @example 900 */
                            expires_in?: number;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User logout
         * @description Invalidate user session and tokens
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout successful */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all clusters
         * @description Retrieve a paginated list of registered clusters
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Page number (1-indexed)
                     * @example 1
                     */
                    page?: components["parameters"]["PageParam"];
                    /**
                     * @description Number of items per page
                     * @example 20
                     */
                    page_size?: components["parameters"]["PageSizeParam"];
                    /** @description Filter by cluster status */
                    status?: "healthy" | "degraded" | "offline";
                    /**
                     * @description Filter by label (format - key:value)
                     * @example environment:production
                     */
                    label?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of clusters */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginationResponse"] & {
                            items?: components["schemas"]["Cluster"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Register new cluster
         * @description Register a new Kubernetes cluster with the control plane
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example production-us-west */
                        name: string;
                        /** @example Production US West */
                        display_name?: string;
                        /** @example Primary production cluster in US West region */
                        description?: string;
                        /**
                         * @example {
                         *       "environment": "production",
                         *       "region": "us-west"
                         *     }
                         */
                        labels?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Cluster registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cluster"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description Cluster already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cluster details
         * @description Retrieve detailed information about a specific cluster
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Cluster identifier
                     * @example cls_abc123
                     */
                    id: components["parameters"]["ClusterIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cluster details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Cluster"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Unregister cluster
         * @description Remove cluster registration from the control plane
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Cluster identifier
                     * @example cls_abc123
                     */
                    id: components["parameters"]["ClusterIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cluster unregistered successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description Cluster cannot be deleted (has active resources) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters/{id}/install-command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Helm install command
         * @description Generate Helm install command with embedded JWT for operator installation
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Cluster identifier
                     * @example cls_abc123
                     */
                    id: components["parameters"]["ClusterIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Installation command generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Complete Helm installation command
                             * @example helm install kubenest-operator oci://ghcr.io/kubenest/operator \
                             *       --set token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... \
                             *       --set clusterId=cls_abc123 \
                             *       --set apiUrl=https://api.kubenest.io/v1
                             */
                            command?: string;
                            /** @description Cluster-specific JWT token */
                            token?: string;
                            /** @description Cluster identifier */
                            cluster_id?: string;
                            /**
                             * Format: date-time
                             * @description Token expiration timestamp
                             */
                            expires_at?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Retrieve a paginated list of projects with optional cluster filter
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Page number (1-indexed)
                     * @example 1
                     */
                    page?: components["parameters"]["PageParam"];
                    /**
                     * @description Number of items per page
                     * @example 20
                     */
                    page_size?: components["parameters"]["PageSizeParam"];
                    /**
                     * @description Filter by cluster ID
                     * @example cls_abc123
                     */
                    cluster_id?: string;
                    /** @description Filter by project phase */
                    phase?: "Pending" | "Ready" | "Failed";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginationResponse"] & {
                            items?: components["schemas"]["Project"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Create project
         * @description Create a new project (namespace) in a cluster
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example api-backend */
                        name: string;
                        /** @example cls_abc123 */
                        cluster_id: string;
                        /** @example API Backend */
                        display_name: string;
                        /** @example Backend API services and databases */
                        description?: string;
                        /** @example dockerhub-credentials */
                        registry_secret?: string;
                        labels?: {
                            [key: string]: string;
                        };
                        annotations?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Project created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description Cluster not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Project already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project details
         * @description Retrieve detailed information about a specific project
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Project identifier
                     * @example proj_xyz789
                     */
                    id: components["parameters"]["ProjectIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete project
         * @description Delete a project and all associated resources
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Project identifier
                     * @example proj_xyz789
                     */
                    id: components["parameters"]["ProjectIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description Project cannot be deleted (has active workloads) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/workloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workloads in project
         * @description Retrieve all workloads within a specific project
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Page number (1-indexed)
                     * @example 1
                     */
                    page?: components["parameters"]["PageParam"];
                    /**
                     * @description Number of items per page
                     * @example 20
                     */
                    page_size?: components["parameters"]["PageSizeParam"];
                };
                header?: never;
                path: {
                    /**
                     * @description Project identifier
                     * @example proj_xyz789
                     */
                    id: components["parameters"]["ProjectIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of workloads */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginationResponse"] & {
                            items?: components["schemas"]["Workload"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List workloads
         * @description Retrieve a paginated list of workloads with optional project filter
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Page number (1-indexed)
                     * @example 1
                     */
                    page?: components["parameters"]["PageParam"];
                    /**
                     * @description Number of items per page
                     * @example 20
                     */
                    page_size?: components["parameters"]["PageSizeParam"];
                    /**
                     * @description Filter by project ID
                     * @example proj_xyz789
                     */
                    project_id?: string;
                    /** @description Filter by workload phase */
                    phase?: "Pending" | "Building" | "Deploying" | "Running" | "Degraded" | "Failed";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of workloads */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginationResponse"] & {
                            items?: components["schemas"]["Workload"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Deploy workload
         * @description Create and deploy a new workload to a project
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example api-server */
                        name: string;
                        /** @example proj_xyz789 */
                        project_id: string;
                        build_mode: components["schemas"]["BuildMode"];
                        /**
                         * @description Container image (required when build_mode is 'image')
                         * @example nginx:1.21
                         */
                        image?: string;
                        git?: components["schemas"]["GitSpec"];
                        /**
                         * @description Builder image for buildpack builds
                         * @example paketobuildpacks/builder:base
                         */
                        builder_image?: string;
                        /**
                         * @default 1
                         * @example 3
                         */
                        replicas?: number;
                        /**
                         * @default 8080
                         * @example 8080
                         */
                        port?: number;
                        resources?: components["schemas"]["ResourceRequirements"];
                        env?: components["schemas"]["EnvVar"][];
                        ingress?: components["schemas"]["IngressSpec"];
                        /**
                         * @example [
                         *       "npm",
                         *       "start"
                         *     ]
                         */
                        command?: string[];
                        /**
                         * @example [
                         *       "--port",
                         *       "8080"
                         *     ]
                         */
                        args?: string[];
                        chart?: components["schemas"]["ChartSpec"];
                        /** @description Custom Helm values */
                        values?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description Workload deployment initiated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workload"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workloads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workload details
         * @description Retrieve detailed information including status and metrics
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workload identifier
                     * @example wl_def456
                     */
                    id: components["parameters"]["WorkloadIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workload details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workload"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete workload
         * @description Delete a workload and all associated resources
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workload identifier
                     * @example wl_def456
                     */
                    id: components["parameters"]["WorkloadIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Workload deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update workload
         * @description Update workload configuration (scale, environment variables, resources)
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workload identifier
                     * @example wl_def456
                     */
                    id: components["parameters"]["WorkloadIdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 5 */
                        replicas?: number;
                        resources?: components["schemas"]["ResourceRequirements"];
                        env?: components["schemas"]["EnvVar"][];
                        /**
                         * @description Update container image (for image build mode)
                         * @example nginx:1.22
                         */
                        image?: string;
                    };
                };
            };
            responses: {
                /** @description Workload updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Workload"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        trace?: never;
    };
    "/workloads/{id}/redeploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger redeployment
         * @description Trigger a redeployment of the workload (useful for git-based builds)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Workload identifier
                     * @example wl_def456
                     */
                    id: components["parameters"]["WorkloadIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redeployment triggered */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Workload redeployment initiated */
                            message?: string;
                            /** @example wl_def456 */
                            workload_id?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/addons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List addons
         * @description Retrieve a paginated list of installed addons
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Page number (1-indexed)
                     * @example 1
                     */
                    page?: components["parameters"]["PageParam"];
                    /**
                     * @description Number of items per page
                     * @example 20
                     */
                    page_size?: components["parameters"]["PageSizeParam"];
                    /**
                     * @description Filter by project ID
                     * @example proj_xyz789
                     */
                    project_id?: string;
                    /** @description Filter by addon type */
                    type?: "postgres" | "redis" | "mysql" | "mongodb" | "kafka" | "rabbitmq" | "custom";
                    /** @description Filter by addon phase */
                    phase?: "Pending" | "Deploying" | "Running" | "Degraded" | "Failed";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of addons */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginationResponse"] & {
                            items?: components["schemas"]["Addon"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /**
         * Install addon
         * @description Install an addon service (database, cache, message queue, etc.)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example postgres-main */
                        name: string;
                        /** @example proj_xyz789 */
                        project_id: string;
                        /**
                         * @example postgres
                         * @enum {string}
                         */
                        type: "postgres" | "redis" | "mysql" | "mongodb" | "kafka" | "rabbitmq" | "custom";
                        chart: components["schemas"]["ChartSpec"];
                        /**
                         * @description Helm chart values
                         * @example {
                         *       "auth": {
                         *         "username": "admin",
                         *         "database": "myapp"
                         *       },
                         *       "primary": {
                         *         "persistence": {
                         *           "size": "10Gi"
                         *         }
                         *       }
                         *     }
                         */
                        values?: Record<string, never>;
                        /**
                         * @default 5m
                         * @example 10m
                         */
                        timeout?: string;
                        /** @default false */
                        create_namespace?: boolean;
                    };
                };
            };
            responses: {
                /** @description Addon installation initiated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Addon"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/addons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get addon details
         * @description Retrieve detailed information including connection details and exports
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Addon identifier
                     * @example addon_ghi789
                     */
                    id: components["parameters"]["AddonIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Addon details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Addon"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Uninstall addon
         * @description Uninstall an addon and remove all associated resources
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Addon identifier
                     * @example addon_ghi789
                     */
                    id: components["parameters"]["AddonIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Addon uninstalled successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description Addon is in use by workloads */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream
         * @description Subscribe to real-time events for clusters, projects, workloads, and addons.
         *
         *     This endpoint uses Server-Sent Events (SSE) to push real-time updates to clients.
         *     Events include lifecycle changes, status updates, and health monitoring.
         *
         *     ## Event Types
         *     - Cluster events: connected, disconnected, heartbeat, status_update
         *     - Project events: create, update, delete, status_update
         *     - Workload events: deploy, scale, restart, delete, rollback, status_update
         *     - Addon events: install, upgrade, uninstall, status_update
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Filter events by cluster ID
                     * @example cls_abc123
                     */
                    cluster_id?: string;
                    /**
                     * @description Filter events by project ID
                     * @example proj_xyz789
                     */
                    project_id?: string;
                    /** @description Filter by resource type */
                    resource_type?: "cluster" | "project" | "workload" | "addon";
                    /**
                     * @description Comma-separated list of event types to subscribe to
                     * @example workload_deploy,workload_status_update
                     */
                    event_types?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream of events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": {
                            /** @description Event type */
                            event?: string;
                            /** @description Event payload (JSON) */
                            data?: Record<string, never>;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        User: {
            /**
             * @description User identifier
             * @example usr_abc123
             */
            id?: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email?: string;
            /** @example John Doe */
            name?: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:00:00Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:00:00Z
             */
            updated_at?: string;
        };
        Cluster: {
            /**
             * @description Cluster identifier
             * @example cls_abc123
             */
            id: string;
            /**
             * @description Cluster name (DNS-compliant)
             * @example production-us-west
             */
            name: string;
            /** @example Production US West */
            display_name?: string;
            /** @example Primary production cluster */
            description?: string;
            /**
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "degraded" | "offline";
            /**
             * @description Installed operator version
             * @example v1.2.3
             */
            operator_version?: string;
            /**
             * @description Kubernetes server version
             * @example v1.28.0
             */
            kubernetes_version?: string;
            /**
             * @description Number of nodes in cluster
             * @example 5
             */
            node_count?: number;
            /** @description Status of installed components */
            components?: {
                argocd?: components["schemas"]["ComponentStatus"];
                cert_manager?: components["schemas"]["ComponentStatus"];
                ingress_nginx?: components["schemas"]["ComponentStatus"];
                vault?: components["schemas"]["ComponentStatus"];
            };
            /** @description Cluster resource metrics */
            metrics?: {
                /** @example 32 */
                cpu_capacity?: string;
                /** @example 128Gi */
                memory_capacity?: string;
                /** @example 30 */
                cpu_allocatable?: string;
                /** @example 120Gi */
                memory_allocatable?: string;
                /** @example 150 */
                pod_count?: number;
                /** @example 330 */
                pod_capacity?: number;
            };
            /**
             * @example {
             *       "environment": "production",
             *       "region": "us-west"
             *     }
             */
            labels?: {
                [key: string]: string;
            };
            /**
             * Format: date-time
             * @description Last heartbeat timestamp
             * @example 2024-01-15T10:30:00Z
             */
            last_heartbeat?: string;
            /**
             * Format: date-time
             * @example 2024-01-10T08:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            updated_at?: string;
        };
        ComponentStatus: {
            /** @example true */
            installed?: boolean;
            /** @example v2.9.0 */
            version?: string;
            /** @example true */
            healthy?: boolean;
        };
        Project: {
            /**
             * @description Project identifier
             * @example proj_xyz789
             */
            id: string;
            /**
             * @description Project name (maps to Kubernetes namespace)
             * @example api-backend
             */
            name: string;
            /**
             * @description Parent cluster identifier
             * @example cls_abc123
             */
            cluster_id: string;
            /** @example API Backend */
            display_name: string;
            /** @example Backend API services */
            description?: string;
            /**
             * @description Registry credentials secret name
             * @example dockerhub-credentials
             */
            registry_secret?: string;
            /**
             * @description Current project phase
             * @example Ready
             * @enum {string}
             */
            phase: "Pending" | "Ready" | "Failed";
            /**
             * @description Kubernetes namespace status
             * @example Active
             */
            namespace_status?: string;
            /**
             * @description Registry secret synchronization status
             * @example Synced
             */
            registry_secret_status?: string;
            labels?: {
                [key: string]: string;
            };
            annotations?: {
                [key: string]: string;
            };
            conditions?: components["schemas"]["Condition"][];
            /**
             * @description Last observed resource generation
             * @example 5
             */
            observed_generation?: number;
            /**
             * Format: date-time
             * @example 2024-01-12T09:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:00:00Z
             */
            updated_at?: string;
        };
        Workload: {
            /**
             * @description Workload identifier
             * @example wl_def456
             */
            id: string;
            /** @example api-server */
            name: string;
            /** @example proj_xyz789 */
            project_id: string;
            build_mode: components["schemas"]["BuildMode"];
            /**
             * @description Container image (current or specified)
             * @example nginx:1.21
             */
            image?: string;
            git?: components["schemas"]["GitSpec"];
            /** @example paketobuildpacks/builder:base */
            builder_image?: string;
            /**
             * @description Desired replicas
             * @example 3
             */
            replicas?: number;
            /**
             * @description Container port
             * @example 8080
             */
            port?: number;
            resources?: components["schemas"]["ResourceRequirements"];
            env?: components["schemas"]["EnvVar"][];
            ingress?: components["schemas"]["IngressSpec"];
            command?: string[];
            args?: string[];
            chart?: components["schemas"]["ChartSpec"];
            /** @description Custom Helm values */
            values?: Record<string, never>;
            /**
             * @description Current workload phase
             * @example Running
             * @enum {string}
             */
            phase: "Pending" | "Building" | "Deploying" | "Running" | "Degraded" | "Failed";
            status?: {
                /**
                 * @description Current running replicas
                 * @example 3
                 */
                replicas?: number;
                /**
                 * @description Number of ready replicas
                 * @example 3
                 */
                ready_replicas?: number;
                /**
                 * @description Associated build request (if any)
                 * @example build-abc123
                 */
                build_request_name?: string;
                /**
                 * @description Helm release name
                 * @example api-server
                 */
                helm_release_name?: string;
                /**
                 * @description Exported values (URLs, endpoints)
                 * @example {
                 *       "url": "https://api.example.com",
                 *       "internal_url": "http://api-server.api-backend.svc.cluster.local:8080"
                 *     }
                 */
                exports?: {
                    [key: string]: string;
                };
            };
            conditions?: components["schemas"]["Condition"][];
            /** @example 3 */
            observed_generation?: number;
            /**
             * Format: date-time
             * @example 2024-01-14T11:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            updated_at?: string;
        };
        Addon: {
            /**
             * @description Addon identifier
             * @example addon_ghi789
             */
            id: string;
            /** @example postgres-main */
            name: string;
            /** @example proj_xyz789 */
            project_id: string;
            /**
             * @description Addon type (hint for export extraction)
             * @example postgres
             * @enum {string}
             */
            type: "postgres" | "redis" | "mysql" | "mongodb" | "kafka" | "rabbitmq" | "custom";
            chart: components["schemas"]["ChartSpec"];
            /** @description Helm chart values */
            values?: Record<string, never>;
            /** @example 5m */
            timeout?: string;
            /** @example false */
            create_namespace?: boolean;
            /**
             * @description Current addon phase
             * @example Running
             * @enum {string}
             */
            phase: "Pending" | "Deploying" | "Running" | "Degraded" | "Failed";
            status?: {
                /** @example postgres-main */
                helm_release_name?: string;
                /** @example 1 */
                helm_release_revision?: number;
                /** @example deployed */
                helm_release_status?: string;
                /**
                 * @description Connection details and exported values
                 * @example {
                 *       "host": "postgres-main.api-backend.svc.cluster.local",
                 *       "port": "5432",
                 *       "database": "myapp",
                 *       "username": "admin",
                 *       "password_secret": "postgres-main-credentials",
                 *       "dsn": "postgresql://admin@postgres-main.api-backend.svc.cluster.local:5432/myapp"
                 *     }
                 */
                exports?: Record<string, never>;
            };
            conditions?: components["schemas"]["Condition"][];
            /** @example 2 */
            observed_generation?: number;
            /**
             * Format: date-time
             * @example 2024-01-13T14:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2024-01-15T09:00:00Z
             */
            updated_at?: string;
        };
        /**
         * @description Build mode for workload deployment:
         *     - `image`: Use pre-built container image
         *     - `dockerfile`: Build from Dockerfile in git repository
         *     - `buildpack`: Build using Cloud Native Buildpacks
         * @example image
         * @enum {string}
         */
        BuildMode: "image" | "dockerfile" | "buildpack";
        GitSpec: {
            /**
             * Format: uri
             * @description Git repository URL
             * @example https://github.com/example/api-server.git
             */
            repo: string;
            /**
             * @description Git reference (branch, tag, or commit SHA)
             * @example main
             */
            ref: string;
            /**
             * @description Path to Dockerfile (for dockerfile build mode)
             * @default Dockerfile
             * @example docker/Dockerfile
             */
            dockerfile_path: string;
            /**
             * @description Build context path
             * @default .
             * @example .
             */
            context_path: string;
        };
        ChartSpec: {
            /**
             * Format: uri
             * @description Helm repository URL
             * @example https://charts.bitnami.com/bitnami
             */
            repo: string;
            /**
             * @description Chart name
             * @example postgresql
             */
            name: string;
            /**
             * @description Chart version (semver)
             * @example 12.1.2
             */
            version: string;
        };
        ResourceRequirements: {
            requests?: {
                /**
                 * @description CPU request (e.g., "100m", "1")
                 * @example 100m
                 */
                cpu?: string;
                /**
                 * @description Memory request (e.g., "128Mi", "1Gi")
                 * @example 256Mi
                 */
                memory?: string;
            };
            limits?: {
                /**
                 * @description CPU limit
                 * @example 1
                 */
                cpu?: string;
                /**
                 * @description Memory limit
                 * @example 512Mi
                 */
                memory?: string;
            };
        };
        EnvVar: {
            /**
             * @description Environment variable name
             * @example DATABASE_URL
             */
            name: string;
            /**
             * @description Literal value
             * @example postgresql://localhost:5432/myapp
             */
            value?: string;
            /** @description Source for the environment variable's value */
            value_from?: {
                /** @description Reference to a Kubernetes Secret */
                secret_key_ref?: {
                    /** @example db-credentials */
                    name?: string;
                    /** @example password */
                    key?: string;
                };
                /** @description Reference to a ConfigMap */
                config_map_key_ref?: {
                    /** @example app-config */
                    name?: string;
                    /** @example api_url */
                    key?: string;
                };
                /** @description Reference to another component's exports */
                export_ref?: {
                    /**
                     * @description Component name (addon or workload)
                     * @example postgres-main
                     */
                    component: string;
                    /**
                     * @description Export key
                     * @example dsn
                     */
                    key: string;
                };
            };
        };
        IngressSpec: {
            /**
             * @default false
             * @example true
             */
            enabled: boolean;
            /**
             * @description Ingress hostname
             * @example api.example.com
             */
            host?: string;
            /**
             * @description URL path prefix
             * @default /
             * @example /api/v1
             */
            path: string;
            tls?: {
                /**
                 * @description TLS certificate secret name
                 * @example api-tls-cert
                 */
                secret_name?: string;
                /**
                 * @example [
                 *       "api.example.com"
                 *     ]
                 */
                hosts?: string[];
            };
            /**
             * @description Ingress annotations
             * @example {
             *       "cert-manager.io/cluster-issuer": "letsencrypt-prod",
             *       "nginx.ingress.kubernetes.io/ssl-redirect": "true"
             *     }
             */
            annotations?: {
                [key: string]: string;
            };
        };
        /** @description Status condition following Kubernetes conventions */
        Condition: {
            /**
             * @description Condition type
             * @example Ready
             */
            type: string;
            /**
             * @description Condition status
             * @example True
             * @enum {string}
             */
            status: "True" | "False" | "Unknown";
            /**
             * @description Machine-readable reason
             * @example DeploymentSucceeded
             */
            reason?: string;
            /**
             * @description Human-readable message
             * @example All replicas are ready
             */
            message?: string;
            /**
             * Format: date-time
             * @description Last time the condition transitioned
             * @example 2024-01-15T10:30:00Z
             */
            last_transition_time: string;
        };
        PaginationResponse: {
            /**
             * @description Total number of items
             * @example 42
             */
            total?: number;
            /**
             * @description Current page number
             * @example 1
             */
            page?: number;
            /**
             * @description Items per page
             * @example 20
             */
            page_size?: number;
            /**
             * @description Total number of pages
             * @example 3
             */
            total_pages?: number;
        };
        Error: {
            /**
             * @description Error code
             * @example validation_error
             */
            error: string;
            /**
             * @description Human-readable error message
             * @example Invalid request parameters
             */
            message: string;
            /**
             * @description Additional error details
             * @example {
             *       "field": "name",
             *       "reason": "must be lowercase alphanumeric with hyphens"
             *     }
             */
            details?: {
                [key: string]: unknown;
            };
            /**
             * @description Request identifier for debugging
             * @example req_abc123xyz
             */
            request_id?: string;
        };
    };
    responses: {
        /** @description Bad request - invalid parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "bad_request",
                 *       "message": "Invalid request parameters",
                 *       "details": {
                 *         "field": "replicas",
                 *         "reason": "must be between 0 and 100"
                 *       },
                 *       "request_id": "req_abc123"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized - missing or invalid authentication */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "unauthorized",
                 *       "message": "Invalid or expired JWT token",
                 *       "request_id": "req_def456"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden - insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "forbidden",
                 *       "message": "Insufficient permissions to perform this action",
                 *       "request_id": "req_ghi789"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "not_found",
                 *       "message": "Resource not found",
                 *       "request_id": "req_jkl012"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "internal_error",
                 *       "message": "An unexpected error occurred",
                 *       "request_id": "req_mno345"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Cluster identifier
         * @example cls_abc123
         */
        ClusterIdParam: string;
        /**
         * @description Project identifier
         * @example proj_xyz789
         */
        ProjectIdParam: string;
        /**
         * @description Workload identifier
         * @example wl_def456
         */
        WorkloadIdParam: string;
        /**
         * @description Addon identifier
         * @example addon_ghi789
         */
        AddonIdParam: string;
        /**
         * @description Page number (1-indexed)
         * @example 1
         */
        PageParam: number;
        /**
         * @description Number of items per page
         * @example 20
         */
        PageSizeParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
